### ISSUE TITLE
Redirect handling in postFormData

### ISSUE THREAD

**Issue by tomnoir** [shopware/k6-shopware#8]
The regex to extract the domain part of the URL seems to miss domain parts if there are several (e.g. subdomain):

https://github.com/shopware/k6-shopware/blob/3a3fc0e0e545ecfffd26f0e6f133a8e3b427863e/helpers/util.js#L37

An improved regex could be `/(https?:\/\/(?:[\w-]+\.)+[\w-]+(?::\d+)?)/g`

Otherwise thanks to everybody for the amazing K6 scenario!

**Comment by shyim** [comment]
Your regex does not match just localhost :)

**Comment by tomnoir** [comment]
Oh you're right 🙈

Thanks for the quick fix!
